# Generated by Django 5.1.7 on 2025-03-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="to'liq ismi")),
                ('phone', models.CharField(max_length=255, verbose_name='nomeri')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='tafsif')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='product nomi')),
                ('status', models.CharField(choices=[('main_page', 'MAIN_PAGE'), ('service', 'SERVICE'), ('get_tt', 'GET_TT'), ('partner', 'PARTNER'), ('order', 'ORDER')], default='main_page', max_length=255, verbose_name='holati')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ismi')),
                ('icon', models.ImageField(upload_to='', verbose_name='iconi')),
                ('order', models.IntegerField(default=0, verbose_name='tartibi')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="to'liq ismi")),
                ('position', models.CharField(max_length=255, verbose_name='lavozimi')),
                ('image', models.ImageField(upload_to='customers/', verbose_name='rasmi')),
                ('deascription', models.TextField(verbose_name='tafsif')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='tafsif')),
                ('image', models.ImageField(upload_to='', verbose_name='rasmi')),
                ('date', models.DateField(verbose_name='vaqti')),
                ('body', models.TextField(max_length=255, verbose_name='yomonliklari')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='rasmi')),
                ('url', models.CharField(max_length=255, verbose_name='urli')),
                ('order', models.IntegerField(default=0, verbose_name='tartibi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('status', models.CharField(max_length=255, verbose_name='holat')),
                ('order', models.IntegerField(default=0, verbose_name='tartibi')),
                ('image', models.ImageField(upload_to='', verbose_name='rasmi')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='tafsif')),
                ('brand', models.CharField(max_length=255, verbose_name='brendi')),
                ('country', models.CharField(max_length=255, verbose_name='mamlakati')),
                ('guarantee', models.CharField(max_length=255, verbose_name='kafaloti')),
                ('is_main_page', models.BooleanField(max_length=255, verbose_name='bosh sahifa')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='kalit')),
                ('value', models.CharField(max_length=255, verbose_name='valeusi')),
                ('order', models.IntegerField(default=0, verbose_name='tartibi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristic', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='rasmi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.product')),
            ],
        ),
    ]
